---
# Source: cf-app/templates/app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-sample-node-chat-demo-app
  namespace: docker
  labels:
    app: cloud-sample-node-chat-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-sample-node-chat-demo-app
  template:
    metadata:
      labels:
        app: cloud-sample-node-chat-demo-app
    spec:
      imagePullSecrets:
        - name: demo-registry-credentials-pull
      containers:
        - name: cloud-sample-node-chat-demo-app
          image: europe-west3-docker.pkg.dev/sap-se-gcp-istio-dev/btp-core-demo/docker/cloud-sample-node-chat:latest
          ports:
            - containerPort: 8089
          volumeMounts:
          - mountPath: /tmp
            name: tmp
      volumes:
      - name: tmp
        emptyDir: {}