---
apiVersion: v1
kind: Service
metadata:
  name: cloud-sample-node-chat-demo-app
spec:
  selector:
    app: cloud-sample-node-chat-demo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8089

---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: cloud-sample-node-chat-demo-app
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: cloud-sample-node-chat-demo-app
    port: 8080
    host: cloud-sample-node-chat-demo-app
  rules:
    - path: /.*
      methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - HEAD
      accessStrategies:
        - handler: allow